version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - kal
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
    custom:
      kal:
        type: module
        description: KAL is the Kube-API-Linter and lints Kube like APIs based on API conventions and best practices.
        settings:
          linters:
            enable:
              - commentstart
              - conditions
              - integers
              - jsontags
              - maxlength
              # NOTE: we have a number of boolean fields. Should we convert them to
              # string?
              # - "nobools"
              - nofloats
              - nophase
              - optionalorrequired
              - requiredfields
              - statussubresource
          lintersConfig:
            conditions:
              isFirstField: Warn
              usePatchStrategy: Ignore
              useProtobuf: Forbid
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - kal
        path-except: api/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
