apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: subnetpools.networking.example.com
spec:
  group: networking.example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cidr:
                  type: string
                description:
                  type: string
            status:
              type: object
              properties:
                state:
                  type: string
  scope: Namespaced
  names:
    plural: subnetpools
    singular: subnetpool
    kind: SubnetPool
    shortNames:
      - spool
