# permissions for end users to view openstackports.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstackport-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orc
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
  name: openstackport-viewer-role
rules:
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackports
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackports/status
  verbs:
  - get
