# permissions for end users to edit openstackflavors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstackflavor-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gophercloud-operator
    app.kubernetes.io/part-of: gophercloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstackflavor-editor-role
rules:
- apiGroups:
  - openstack.gophercloud.io
  resources:
  - openstackflavors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.gophercloud.io
  resources:
  - openstackflavors/status
  verbs:
  - get
