# permissions for end users to view openstacksecuritygrouprules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstacksecuritygrouprule-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gophercloud-operator
    app.kubernetes.io/part-of: gophercloud-operator
    app.kubernetes.io/managed-by: kustomize
  name: openstacksecuritygrouprule-viewer-role
rules:
- apiGroups:
  - openstack.gophercloud.io
  resources:
  - openstacksecuritygrouprules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.gophercloud.io
  resources:
  - openstacksecuritygrouprules/status
  verbs:
  - get
