# permissions for end users to edit openstacksecuritygrouprules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstacksecuritygrouprule-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gopherkube
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
  name: openstacksecuritygrouprule-editor-role
rules:
- apiGroups:
  - gopherkube.dev
  resources:
  - openstacksecuritygrouprules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gopherkube.dev
  resources:
  - openstacksecuritygrouprules/status
  verbs:
  - get
