# permissions for end users to edit openstackimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstackimage-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-resource-controller
    app.kubernetes.io/part-of: openstack-resource-controller
    app.kubernetes.io/managed-by: kustomize
  name: openstackimage-editor-role
rules:
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackimages/status
  verbs:
  - get
