# permissions for end users to view openstacksecuritygroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: openstacksecuritygroup-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: openstack-resource-controller
    app.kubernetes.io/part-of: openstack-resource-controller
    app.kubernetes.io/managed-by: kustomize
  name: openstacksecuritygroup-viewer-role
rules:
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksecuritygroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksecuritygroups/status
  verbs:
  - get
