---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackclouds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackclouds/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackclouds/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackflavors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackflavors/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackflavors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackfloatingips
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackfloatingips/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackfloatingips/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackimages/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackimages/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackkeypairs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackkeypairs/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackkeypairs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacknetworks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacknetworks/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacknetworks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackports/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackports/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackrouters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackrouters/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackrouters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksecuritygrouprules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksecuritygrouprules/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksecuritygrouprules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksecuritygroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksecuritygroups/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksecuritygroups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackservers/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstackservers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksubnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksubnets/finalizers
  verbs:
  - update
- apiGroups:
  - openstack.k-orc.cloud
  resources:
  - openstacksubnets/status
  verbs:
  - get
  - patch
  - update
