name: Feature Request
description: Something is missing
type: Feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: textarea
    id: request
    attributes:
      label: What would you like to see implemented?
      description: This could be adding support for a new type of OpenStack resource, a missing field, etc.
      placeholder: Tell us what you'd like ORC to do.
    validations:
      required: true
  - type: textarea
    id: reason
    attributes:
      label: Additional information
      description: Tell us why you think this is important. Describe your use case.
  - type: input
    id: reference-doc
    attributes:
      label: Link to reference documentation
      description: "Please link to the OpenStack reference documentation, if applicable"
      placeholder: "Example: https://docs.openstack.org/api-ref/network/v2/index.html#ports"
