apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackNetwork
metadata:
  labels:
    app.kubernetes.io/name: openstacknetwork
    app.kubernetes.io/instance: openstacknetwork-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: openstacknetwork-sample
spec:
  # TODO(user): Add fields here
