apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackKeypair
metadata:
  labels:
    app.kubernetes.io/name: openstackkeypair
    app.kubernetes.io/instance: openstackkeypair-sample
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: mykey
spec:
  cloud: osp1
  resource:
    name: mykey
    publicKey: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFlYK/koCWHk203WOT8tA8PQtUx1ox+bJZMt9wQrcAa+'
