apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackNetwork
metadata:
  labels:
    app.kubernetes.io/name: openstacknetwork
    app.kubernetes.io/instance: openstacknetwork-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: external
spec:
  cloud: osp1
  id: 316eeb47-1498-46b4-b39e-00ddf73bd2a5 # REPLACE with the ID of the existing external network
  unmanaged: true
---
apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackNetwork
metadata:
  labels:
    app.kubernetes.io/name: openstacknetwork
    app.kubernetes.io/instance: openstacknetwork-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: network-1
spec:
  cloud: osp1
  name: my-new-network
