apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackPort
metadata:
  labels:
    app.kubernetes.io/name: openstackport
    app.kubernetes.io/instance: openstackport-sample
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: port-1
spec:
  cloud: osp1
  resource:
    network: network-1
    securityGroups:
      - workstation
    fixedIPs:
      - subnet: network-1-subnet-1
        ipAddress: 192.168.1.55
    name: port-1
    description: Ceci est une description.
