apiVersion: openstack.gophercloud.io/v1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-sample
    app.kubernetes.io/part-of: gophercloud-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gophercloud-operator
  name: openstacksecuritygrouprule-sample
spec:
  # TODO(user): Add fields here
