apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackSecurityGroup
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygroup
    app.kubernetes.io/instance: openstacksecuritygroup-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: default
spec:
  cloud: osp1
  id: 4fa1f154-9730-4d9a-8cc3-da0001ec9f86 # REPLACE with the ID of the existing "default" security group
  unmanaged: true
---
apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackSecurityGroup
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygroup
    app.kubernetes.io/instance: openstacksecuritygroup-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: workstation
spec:
  cloud: osp1
  name: workstation
  description: 'For remote work'
