apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackFloatingIP
metadata:
  labels:
    app.kubernetes.io/name: openstackfloatingip
    app.kubernetes.io/instance: openstackfloatingip-sample
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: fip-1
spec:
  cloud: osp1
  resource:
    description: Provisioned by openstack-resource-controller
    floatingNetwork: external
