apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackCloud
metadata:
  labels:
    app.kubernetes.io/name: openstackcloud
    app.kubernetes.io/instance: openstackcloud-sample
    app.kubernetes.io/part-of: openstack-resource-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: openstack-resource-controller
  name: osp1
spec:
  cloud: openstack # REPLACE with the name of the target cloud in clouds.yaml
  credentials:
    source: secret
    secretRef:
      name: openstack-clouds
      key: clouds.yaml
