apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackRouter
metadata:
  labels:
    app.kubernetes.io/name: openstackrouter
    app.kubernetes.io/instance: openstackrouter-sample
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: router-1
spec:
  cloud: osp1
  name: router-1
  externalGatewayInfo:
    network: external
  subnets:
    - network-1
