apiVersion: openstack.gophercloud.io/v1
kind: OpenStackServer
metadata:
  labels:
    app.kubernetes.io/name: openstackserver
    app.kubernetes.io/instance: openstackserver-sample
    app.kubernetes.io/part-of: gophercloud-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gophercloud-operator
  name: openstackserver-sample
spec:
  # TODO(user): Add fields here
