apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackImage
metadata:
  labels:
    app.kubernetes.io/name: openstackimage
    app.kubernetes.io/instance: openstackimage-sample
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: fedora
spec:
  cloud: osp1
  resource:
    name: fedora-39
    containerFormat: bare
    diskFormat: qcow2
    method: web-download
    webDownload:
      url: https://download.fedoraproject.org/pub/fedora/linux/releases/39/Cloud/x86_64/images/Fedora-Cloud-Base-39-1.5.x86_64.qcow2
