apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroup
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygroup
    app.kubernetes.io/instance: openstacksecuritygroup-sample
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: default
spec:
  cloud: osp1
  id: 01951585-93f7-42c9-9dee-37ce0d476bb2 # REPLACE with the ID of the existing "default" security group
  unmanaged: true
---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackSecurityGroup
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygroup
    app.kubernetes.io/instance: openstacksecuritygroup-sample
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: workstation
spec:
  cloud: osp1
  resource:
    name: workstation
    description: 'For remote work'
