apiVersion: openstack.k-orc.cloud/v1alpha1
kind: OpenStackServer
metadata:
  labels:
    app.kubernetes.io/name: openstackserver
    app.kubernetes.io/instance: openstackserver-sample
    app.kubernetes.io/part-of: orc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: orc
  name: workstation
spec:
  cloud: osp1
  name: workstation
  image: fedora
  flavor: small
  networks:
  - network-1
  securityGroups:
  - workstation
