apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: workstation-ssh-ipv4
spec:
  cloud: osp1
  securityGroup: workstation
  direction: ingress
  description: ssh
  portRangeMin: 22
  portRangeMax: 22
  protocol: TCP
  etherType: IPv4
---
apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: workstation-mosh-ipv4
spec:
  cloud: osp1
  securityGroup: workstation
  direction: ingress
  description: mosh
  portRangeMin: 60000
  portRangeMax: 61000
  protocol: UDP
  etherType: IPv4
---
apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: workstation-ssh-ipv6
spec:
  cloud: osp1
  securityGroup: workstation
  direction: ingress
  description: ssh
  portRangeMin: 22
  portRangeMax: 22
  protocol: TCP
  etherType: IPv6
---
apiVersion: openstack.gopherkube.dev/v1alpha1
kind: OpenStackSecurityGroupRule
metadata:
  labels:
    app.kubernetes.io/name: openstacksecuritygrouprule
    app.kubernetes.io/instance: openstacksecuritygrouprule-sample
    app.kubernetes.io/part-of: gopherkube
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: gopherkube
  name: workstation-mosh-ipv6
spec:
  cloud: osp1
  securityGroup: workstation
  direction: ingress
  description: mosh
  portRangeMin: 60000
  portRangeMax: 61000
  protocol: UDP
  etherType: IPv6
