---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Server
metadata:
  name: server
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  resource:
    imageRef: image
    flavorRef: flavor
    ports:
    - portRef: port
