---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Server
metadata:
  name: public-server
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: dev-test-cloud-config
  managementPolicy: managed
  resource:
    imageRef: public-server-image
    flavorRef: public-server-flavor
    ports:
    - portRef: public-server-port
