# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/openstack.k-orc.cloud_openstackclouds.yaml
- bases/openstack.k-orc.cloud_openstackflavors.yaml
- bases/openstack.k-orc.cloud_openstackfloatingips.yaml
- bases/openstack.k-orc.cloud_openstackimages.yaml
- bases/openstack.k-orc.cloud_openstacknetworks.yaml
- bases/openstack.k-orc.cloud_openstacksecuritygrouprules.yaml
- bases/openstack.k-orc.cloud_openstacksecuritygroups.yaml
- bases/openstack.k-orc.cloud_openstackservers.yaml
- bases/openstack.k-orc.cloud_openstacksubnets.yaml
- bases/openstack.k-orc.cloud_openstackrouters.yaml
- bases/openstack.k-orc.cloud_openstackports.yaml
- bases/openstack.k-orc.cloud_openstackkeypairs.yaml
#+kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- path: patches/webhook_in_openstackclouds.yaml
#- path: patches/webhook_in_openstackflavors.yaml
#- path: patches/webhook_in_openstackfloatingips.yaml
#- path: patches/webhook_in_openstackimages.yaml
#- path: patches/webhook_in_openstacknetworks.yaml
#- path: patches/webhook_in_openstacksecuritygrouprules.yaml
#- path: patches/webhook_in_openstacksecuritygroups.yaml
#- path: patches/webhook_in_openstackservers.yaml
#- path: patches/webhook_in_openstacksubnets.yaml
#- path: patches/webhook_in_openstackrouters.yaml
#- path: patches/webhook_in_openstackports.yaml
#- path: patches/webhook_in_openstackkeypairs.yaml
#+kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- path: patches/cainjection_in_openstackclouds.yaml
#- path: patches/cainjection_in_openstackflavors.yaml
#- path: patches/cainjection_in_openstackfloatingips.yaml
#- path: patches/cainjection_in_openstackimages.yaml
#- path: patches/cainjection_in_openstacknetworks.yaml
#- path: patches/cainjection_in_openstacksecuritygrouprules.yaml
#- path: patches/cainjection_in_openstacksecuritygroups.yaml
#- path: patches/cainjection_in_openstackservers.yaml
#- path: patches/cainjection_in_openstacksubnets.yaml
#- path: patches/cainjection_in_openstackrouters.yaml
#- path: patches/cainjection_in_openstackports.yaml
#- path: patches/cainjection_in_openstackkeypairs.yaml
#+kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
