---
apiVersion: openstack.k-orc.cloud/v1alpha1
kind: Image
metadata:
  name: cirros
spec:
  cloudCredentialsRef:
    cloudName: openstack
    secretName: cloud-config
  managementPolicy: managed
  resource:
    tags:
    - orc-test
    properties:
      hardware:
        diskBus: "scsi"
        scsiModel: "virtio-scsi"
        rngModel: "virtio"
        qemuGuestAgent: True
    content:
      diskFormat: qcow2
      download:
        url: https://github.com/k-orc/openstack-resource-controller/raw/2ddc1857f5e22d2f0df6f5ee033353e4fd907121/internal/controllers/image/testdata/cirros-0.6.3-x86_64-disk.img
