name: container image

on:
  push:
    branches:
    - main

permissions:
  contents: read

env:
  image_tag_branch: quay.io/orc/openstack-resource-controller:branch-${GITHUB_REF_NAME}
  image_tag_commit: quay.io/orc/openstack-resource-controller:commit-${GITHUB_SHA::7}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - run: |
        docker login -u="${{ secrets.QUAY_USERNAME }}" -p="${{ secrets.QUAY_TOKEN }}" quay.io
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.image_tag_branch }} --push .
        docker buildx build --platform linux/amd64,linux/arm64 -t ${{ env.image_tag_commit }} --label quay.expires-after=4w --push .
