name: e2e

on:
  pull_request:

permissions:
  contents: read

jobs:
  e2e:
    name: Run acceptance tests against OpenStack ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: "zed"
            openstack_version: "stable/zed"
            ubuntu_version: "20.04"
          - name: "bobcat"
            openstack_version: "stable/2023.2"
            ubuntu_version: "22.04"
    env:
      image_tag: virtual-registry.k-orc.cloud/ci:commit-${GITHUB_SHA::7}

    runs-on: ubuntu-${{ matrix.ubuntu_version }}

    steps:
    - uses: actions/checkout@v4

    - name: Deploy devstack
      uses: EmilienM/devstack-action@40c77372dbc135a17adc877eb77fc226a134305c
      with:
        enable_workaround_docker_io: 'false'
        branch: ${{ matrix.openstack_version }}

    - name: Deploy a Kind Cluster
      uses: helm/kind-action@dda0770415bac9fc20092cacbc54aa298604d140
      with:
        cluster_name: orc

    - name: Build and push a container image to Kind
      run: |
        docker build -t ${{ env.image_tag }} .
        kind load docker-image ${{ env.image_tag }} ${{ env.image_tag }} --name orc

    - name: Deploy orc
      run: |
        kubectl config use-context kind-orc
        make deploy IMG=${{ env.image_tag }}

    - name: Apply simple-server
      run: |
        cp /etc/openstack/clouds.yaml config/samples/simple-server/
        kubectl apply -k config/samples/simple-server
        kubectl wait --timeout=10m --for=condition=ready OpenStackServer workstation

    - name: Inspect the server
      run: |
        openstack server show "$(kubectl get openstackserver workstation -o jsonpath='{.status.resource.id}')"
      env:
        OS_CLOUD: devstack
