on: [push, pull_request]
name: go fmt
permissions:
  contents: read

jobs:
  go-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1'

      - uses: actions/checkout@v4

      - run: |
          test -z "$(gofmt -e -d . | tee /dev/stderr)"
