on:
  push:
    branches:
    - main
  pull_request:
name: go fmt
permissions:
  contents: read

jobs:
  go-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1'

      - run: |
          test -z "$(gofmt -e -d . | tee /dev/stderr)"
