on:
  push:
    branches:
    - main
  pull_request:
name: go lint
permissions:
  contents: read

jobs:
  go-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1'

      - run: |
          make lint 
          make verify-fmt
