on: [push, pull_request]
name: go mod
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1'

      - uses: actions/checkout@v4

      - run: |
          if [ $(go mod tidy && git diff | wc -l) -gt 0 ]; then git diff && exit 1; fi
