on: [push, pull_request]
name: go vet
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1'

      - uses: actions/checkout@v4

      - run: |
          go vet ./...
