on:
  push:
    branches:
    - main
    paths:
    - 'website/**'
    - 'api/v1alpha1/**'
    - '.github/workflows/website.yaml'
name: website

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install crd docs generator
      run: go install github.com/elastic/crd-ref-docs@15438a197f339a5b68be2e622725327c3e367811

    - name: Pip install
      run: pip install -Ur website/requirements.txt

    - name: Generate reference
      run: /home/runner/go/bin/crd-ref-docs --config=website/crd-ref-docs-config.yaml --output-path=website/docs/reference.md --source-path=api/v1alpha1 --renderer=markdown

    - name: Build the site
      run: mkdocs build --verbose --strict --config-file website/mkdocs.yml --site-dir rendered

    - name: Publish to Cloudflare Pages
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: k-orc
        directory: website/rendered
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
